### PR TITLE
Use GO_SERVER_URL env var instead of only GO_SERVER

### PR DESCRIPTION
**Pull request by arvindsv**
For https://github.com/gocd/gocd-docker/issues/66

### CODE REVIEW

**Comment by arvindsv** [comment]
I've verified that both these work:

```
docker run -ti -e GO_SERVER=192.168.0.123 -e GO_SERVER_PORT=8154 gocd-agent
```

```
docker run -ti -e GO_SERVER_URL=https://192.168.0.123:8154/go gocd-agent
```

**Comment by mansab** [comment]
We've tried building a docker image from your changes but it still fails while launching the gocd-agent with the following error:

```
muppal@eumuppal  ~  docker run -it -e GO_SERVER_URL=https://10.1.11.71:32771/go mansab/gocd-agent:arvindsv
*** Running /etc/rc.local...
*** Booting runit daemon...
*** Runit started as PID 8
Starting Go Agent to connect to server go-server ...
sed: -e expression #1, char 40: unknown option to `s'
[Fri Jan 13 14:54:30 UTC 2017] using default settings from /etc/default/go-agent
logFile Environment Variable= null
Logging to go-agent-bootstrapper.log
0 [TouchLoopThread-2] INFO com.thoughtworks.go.agent.launcher.Lockfile  - Using lock file: /var/lib/go-agent/.agent-bootstrapper.running
Jan 13 14:54:30 956ef6a45373 syslog-ng[14]: syslog-ng starting up; version='3.5.3'
439 [main] ERROR com.thoughtworks.go.agent.launcher.ServerCall  - Couldn't access Go Server with base url: https://127.0.0.1:8154/go/admin/agent-launcher.jar: org.apache.http.conn.HttpHostConnectException: Connect to 127.0.0.1:8154 [/127.0.0.1] failed: Connection refused (Connection refused)
java.lang.Exception: Couldn't access Go Server with base url: https://127.0.0.1:8154/go/admin/agent-launcher.jar: org.apache.http.conn.HttpHostConnectException: Connect to 127.0.0.1:8154 [/127.0.0.1] failed: Connection refused (Connection refused)
	at com.thoughtworks.go.agent.launcher.ServerCall.invoke(ServerCall.java:78)
	at com.thoughtworks.go.agent.launcher.ServerBinaryDownloader.headers(ServerBinaryDownloader.java:130)
	at com.thoughtworks.go.agent.launcher.ServerBinaryDownloader.downloadIfNecessary(ServerBinaryDownloader.java:106)
	at com.thoughtworks.go.agent.launcher.AgentLauncherImpl.launch(AgentLauncherImpl.java:78)
	at com.thoughtworks.go.agent.bootstrapper.AgentBootstrapper.go(AgentBootstrapper.java:72)
	at com.thoughtworks.go.agent.bootstrapper.AgentBootstrapper.main(AgentBootstrapper.java:54)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at com.simontuffs.onejar.Boot.run(Boot.java:306)
	at com.simontuffs.onejar.Boot.main(Boot.java:159)
Caused by: org.apache.http.conn.HttpHostConnectException: Connect to 127.0.0.1:8154 [/127.0.0.1] failed: Connection refused (Connection refused)
	at org.apache.http.impl.conn.DefaultHttpClientConnectionOperator.connect(DefaultHttpClientConnectionOperator.java:158)
	at org.apache.http.impl.conn.PoolingHttpClientConnectionManager.connect(PoolingHttpClientConnectionManager.java:353)
	at org.apache.http.impl.execchain.MainClientExec.establishRoute(MainClientExec.java:380)
	at org.apache.http.impl.execchain.MainClientExec.execute(MainClientExec.java:236)
	at org.apache.http.impl.execchain.ProtocolExec.execute(ProtocolExec.java:184)
	at org.apache.http.impl.execchain.RetryExec.execute(RetryExec.java:88)
	at org.apache.http.impl.execchain.RedirectExec.execute(RedirectExec.java:110)
	at org.apache.http.impl.client.InternalHttpClient.doExecute(InternalHttpClient.java:184)
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:82)
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:107)
	at com.thoughtworks.go.agent.launcher.ServerCall.invoke(ServerCall.java:55)
	... 11 more
```

We suspect the issue is with the [sed replace line](https://github.com/gocd/gocd-docker/pull/67/files#diff-0c62882ebb689ba6174f33807bb9e192R11) which works for mac but not inside the container (which is Ubuntu). 

So, we tried to debug it a bit and came up with the following sed replace statement (which works):

```
sed -i -e "s@GO_SERVER_URL=.*@GO_SERVER_URL=${GO_SERVER_URL}@" /etc/default/go-agent
```

**Comment by arvindsv** [comment]
@mansab: You're right. Sorry about that! I don't know how my test worked. I'll verify it properly, again, now. I haven't tried your change yet, but it makes sense to me, since the slash in the GO_SERVER_URL can conflict with the slash in the sed expression. Changing it to @ (or something else) should be fine. Let me take a look.

**Comment by arvindsv** [comment]
Fixed. Should work now. I incorporated your suggestion. Thanks!

**Pull request merged**
